name: flutter_widget_switcher
description: A new Flutter package.
version: 0.0.1
author: Jonas Zebari <jonaszebari@gmail.com>
homepage: https://github.com/jonas-zebari/flutter_widget_switcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
